name: Deploy

on:
  push:
    branches: ["master"]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: pages
  cancel-in-progress: true

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Install Rust
        run: rustup toolchain install stable --profile minimal

      - name: Setup Pages
        uses: actions/configure-pages@v2

      - name: Cache Rust Builds
        uses: Swatinem/rust-cache@v2

      - name: Install mdBook
        run: cargo install mdbook

      - name: Build
        run: mdbook build

      - name: Upload Artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: ./book

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1
